name: Godot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  export:
    name: Export ${{ matrix.target }}
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3
    strategy:
      matrix:
        target: [Windows, Linux]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Export for ${{ matrix.target }}
        run: |
          mkdir -p builds/${{ matrix.target }}
          if [ "${{ matrix.target }}" == "Windows" ]; then
            godot --headless --export-release "Windows" builds/Windows/game.exe
          elif [ "${{ matrix.target }}" == "Linux" ]; then
            godot --headless --export-release "Linux" builds/Linux/game.x86_64
          fi

      - name: Upload Artifacts (${{ matrix.target }})
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.target }}
          path: builds/${{ matrix.target }}/
